### ISSUE TITLE
[BUG] Image missing probably

### ISSUE THREAD

**Issue by SashoStoichkov** [Vyvy-vi/Vyvy-vi#10]
**Description**
There seems to be a problem with this image on your profile

**Screenshots**
![image](https://user-images.githubusercontent.com/24972335/107878139-4f295700-6ed9-11eb-9527-542222eb9b48.png)

You can also join the discord community [here](http://discord.eddiehub.org)

Feel free to check out other cool repositories of EddieHub [here](http://github.eddiehub.org)

**Comment by Vyvy-vi** [comment]
Oh, I was testing out a theory
