### ISSUE TITLE
Update Readme following discussion on discord

### ISSUE THREAD

**Issue by ChinmayMhatre** [Vyvy-vi/Vyvy-vi#6]
- remove the joe-username folder
- remove those mint-coloured badges
- remove the section titled Problem OF THE DAY
- remove the profile views badge
- added twitter link

**Comment by Vyvy-vi** [comment]
maybe, you could copy the convo from there, in the description?

**Comment by ChinmayMhatre** [comment]
I updated the description with only the changes that I have made is that fine?

**Comment by Vyvy-vi** [comment]
That's good 👍

**Comment by ChinmayMhatre** [comment]
check out the pr . let me know if it's good.
